version: "3"

services:
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      HOST: ':8081'
    volumes:
      - ./consumer:/code

  producer:
      build:
        context: ./consumer
        dockerfile: Dockerfile
      ports:
        - "8082:8082"
      environment:
        HOST: ':8082'
      volumes:
        - ./producer:/code
      entrypoint: go run main.go

  postgres:
    image: postgres:12
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ${PWD}/docker/postgres-entrypoint.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ${PWD}/docker/pg-dump.sql:/tmp/pg-dump.sql
    logging:
      driver: none

  broker:
    image: pactfoundation/pact-broker:latest
    ports:
      - "9393:9393"
    depends_on:
      - postgres
    environment:
      PACT_BROKER_CONF: /tmp/pact_broker.yml
      PACT_BROKER_PORT_ENVIRONMENT_VARIABLE_NAME: PORT
      PACT_BROKER_DATABASE_URL_ENVIRONMENT_VARIABLE_NAME: DATABASE_URL
      DATABASE_URL: "postgres://postgres:password@postgres/postgres"
      PACT_BROKER_DATABASE_CLEAN_ENABLED: "false"
      PACT_BROKER_DATABASE_CLEAN_CRON_SCHEDULE: "* * * * *"
      PACT_BROKER_DATABASE_CLEAN_DRY_RUN: "false"
      PACT_BROKER_DATABASE_CLEAN_DELETION_LIMIT: "500"
      PACT_BROKER_SQL_LOG_WARN_DURATION: "60"
      # Keep all prod versions, AND the latest version for every pacticipant/tag, and all versions less than 30 days old
      PACT_BROKER_DATABASE_CLEAN_KEEP_VERSION_SELECTORS: '[{"latest": true, "tag": true}, {"max_age": 30}]'
      PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "10"
      PORT: '9393'
      # PACT_BROKER_LOG_LEVEL: DEBUG
      # PACT_BROKER_SQL_LOG_LEVEL: NONE
      # PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "5"
    volumes:
      - ./docker/pact_broker.yml:/tmp/pact_broker.yml